### ISSUE TITLE
Плагины для частичной автоматизации проверок

### ISSUE THREAD

**Issue by EnergoStalin** [s21toolkit/s21cli#2]
# Фича
После клонирования проекта если установлен плагин для проекта запускать его. Что бы если кто то уже проверил проект и законтрибьютил плагин другие могли им воспользоватся что бы проверить себя или других тратя меньше времени на то что может быть автоматизированно.

> [!IMPORTANT]  
> Плагин не зависит от s21cli напрямую со стороны cli будет только хук вызывающий плагины из глобального node_modules.

# Плагин
Что бы модуль считался плагином его имя должно начитаться с s21cli_\<Название проекта как на gitlab без номера попытки\>

Плагин должен иметь такой интерфейс
```ts
export function run(projectRoot: string) {}
```

## Формат рапорта
В основном вольный но для стандартизации что то похожее на это

> [!IMPORTANT]
> Весь вывод должен быть в stdout опционально в файл

> [!NOTE]
> Факт - Любое утверждение о проверочных критериях например "Все пункты оформлены как заголовки второго уровня"

<Факт> - <Статус>

В случае статуса ❌ рапортавать ошибки в виде

> [!NOTE]
> Файл - кликабельная ссылка в формате vscode с номером строки если возможно

<Факт> - <Статус>
<Файл>
<Файл>
<Файл>
...

Статусы:
- ✅
- ❌

### node_modules/s21cli_C4_s21_math/index.js
```js
import { existsSync } from "fs";
import { join } from "path";

export function run(projectRoot) {
	const makefile = join(projectRoot, "src", "Makefile")
	const header = join(projectRoot, "src", "s21_math.h")

	if(existsSync(makefile)) {
		console.log("Мейкфайл в src ✅");
	} else {
		console.log("Мейкфайл в src ❌");
		console.log(`${makefile}`);
	}

	if(existsSync(header)) {
		console.log("s21_math.h в src ✅");
	} else {
		console.log("s21_math.h в src ❌");
		console.log(`${header}`);
	}
}
```

**Comment by bgenia** [comment]
А можно привести пример(ы) такого плагина?

**Comment by EnergoStalin** [comment]
# node_modules/s21cli_C4_s21_math/index.js
```js
import { existsSync } from "fs";
import { join } from "path";

export function run(projectRoot) {
	const makefile = join(projectRoot, "src", "Makefile")
	const header = join(projectRoot, "src", "s21_math.h")

	if(existsSync(makefile)) {
		console.log("Мейкфайл в src ✅");
	} else {
		console.log("Мейкфайл в src ❌");
		console.log(`${makefile}`);
	}

	if(existsSync(header)) {
		console.log("s21_math.h в src ✅");
	} else {
		console.log("s21_math.h в src ❌");
		console.log(`${header}`);
	}
}
```

**Comment by bgenia** [comment]
Закрываю в пользу более общей ишью на поддержку плагинов #12
